spring:
  cache:
    type: none
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        format_sql: true
    hibernate:
      ddl-auto: validate
  datasource:
    name: test
    url: jdbc:mysql://localhost:3306/demodb?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: yaruha
    password: 123


